### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by chinmoyrick** [GuyLewin/pyAS3992#1]
![image](https://cloud.githubusercontent.com/assets/11712316/19022248/722773fe-88f1-11e6-8661-1e87a0ddada8.png)

**Comment by chinmoyrick** [comment]
![image](https://cloud.githubusercontent.com/assets/11712316/19022254/ad9ca936-88f1-11e6-9d17-06a50444ffd5.png)

**Comment by GuyLewin** [comment]
It seems by the right nano open that there's a typo in your as3992_api.py file.
It should be:
`
TTY_USB_WILDCARD = "/dev/ttyUSB*"
`
Like in the GitHub file.
Other than that, make sure that you copied the rest of the file, since every typo might affect

**Comment by chinmoyrick** [comment]
![image](https://cloud.githubusercontent.com/assets/11712316/19103663/d4c1f132-8af5-11e6-9d80-f09053139541.png)
I think its working ..grate job ..thank you..

**Comment by chinmoyrick** [comment]
Hello, I have some problem with python coad
before uploading the code I got a simple and clear hello world message in my serial for restarting the connected device
![image](https://cloud.githubusercontent.com/assets/11712316/19105213/79281186-8afe-11e6-8e00-219bd2e4b703.png)
this is my python code for reading data from antena through serial monitor
![image](https://cloud.githubusercontent.com/assets/11712316/19105219/88cbc3d0-8afe-11e6-951d-d2912cfbe3ee.png)
it runs smoothly first time.​
after executing the code when I restart the connected device the serial monitor shows like that
![image](https://cloud.githubusercontent.com/assets/11712316/19105239/a61ca97c-8afe-11e6-83c6-fa2d886a83e2.png)

​this is the output of serial monitor minicom ...after I run python code and result the connected device ..
from that time when ever I run the same python code it shows an error
![image](https://cloud.githubusercontent.com/assets/11712316/19105247/b4342508-8afe-11e6-99ea-dfd93d159935.png)

**Comment by GuyLewin** [comment]
Can you take a screenshot of the as3992_api.py on your Raspberry Pi device?

**Comment by chinmoyrick** [comment]
hi .
its working now ,there is some connection cable problem arrive that time .. 
one thinking arrive in my mind if you don't mind . what happen if port no  changed after switch of raspberry pi . so there is same time error arrived that time . so can we check witch port connect with pi then go through this port ..<i relay don't know vast about python code  >
next thing  "Can we collect reader data continue as a loop function."or when a new card in reader range  it print it easily ..

**Comment by GuyLewin** [comment]
You can just open a pull request to fix that if you'd like 😄 
And I'm glad it's working now!
