### ISSUE TITLE
STA IR 0507 E RFID

### ISSUE THREAD

**Issue by chinmoyrick** [GuyLewin/pyAS3992#2]
hi.

i have a new reader module , name **STA IR 0507 E RFID**
internally this module have as3992 chip inside ,there is two type of communication  comport and tcp ip port. 
need to implement socket code in python , connect device access over local ip.
in my first test reader plug with 192.168.0.200 ip in my router , and with demo windows software i can access this reader over ip connection ..
need python sketch .....

```
import socket


readerIP = "192.168.0.200"
readerPort = 100

def command(cmd):
	try:
		s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.SOL_TCP)
		s.connect((readerIP, readerPort))
	except:
		raise Exception('NetworkError: Socket creation failed.')
	
	s.send(cmd)
	return s.recv(2048)
```

I need your help to shootout this project

**Comment by GuyLewin** [comment]
I opened up the communication DLL that I found online for your device, and saw this implementation of GetFirmwareVersion
![screen shot 2016-12-17 at 14 54 56](https://cloud.githubusercontent.com/assets/16872/21286912/ec61a79a-c468-11e6-9181-85fd900752a8.png)
It is different than my code for AS3992, and also their send calculates checksums and such.
It's not so difficult to write a Python client for your device as well (by looking at what this DLL does). If you want my help, you can continue the discussion through my email, guy@lewin.co.il
